# CircleCI 2.0 configuration file
version: 2.1

orbs:
  codacy: codacy/base@2.2.1
  codacy_plugins_test: codacy/plugins-test@0.8.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Setup environment
          command: |
            echo 'export COMPOSER_HOME="$HOME/.composer"' >> $BASH_ENV
            echo 'export PATH="$HOME/bin:$COMPOSER_HOME/vendor/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install the tool
          command: |
            sudo apt-get -y update
            sudo apt install ca-certificates apt-transport-https
            wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
            echo "deb https://packages.sury.org/php/ stretch main" | sudo tee /etc/apt/sources.list.d/php.list
            sudo apt-get -y update
            sudo apt-get -y install php5.6 php5.6-common php5.6-xml
            mkdir -p $HOME/bin
            curl -sS https://getcomposer.org/installer | php -- --install-dir=$HOME/bin --filename=composer
            composer global require "sebastian/phpcpd=`cat .phpcpd-version`"
      - run:
          name: Test
          command: sbt coverage test coverageReport
      - run:
          name: Send results to Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
      - run:
          name: Store test reports
          command: |
            mkdir -p coverage-reports/scoverage
            cp -f target/scala-2.13/coverage-report/cobertura.xml coverage-reports/scoverage/results.xml
      - store_test_results:
          path: coverage-reports
      - store_artifacts:
          path: target/scala-2.13/coverage-report
      - store_artifacts:
          path: target/scala-2.13/scoverage-report
      - store_artifacts:
          path: target/scala-2.13/scoverage-data

workflows:
  version: 2
  test_and_publish:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: sbt_dependencies
          cmd: |
            sbt update
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: compile
          cmd: |
            sbt compile test:compile
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
            - sbt_dependencies
      - test:
          requires:
            - compile
      - codacy/sbt:
          name: lint
          cmd: |
            sbt -mem 2048 "set scalafmtUseIvy in ThisBuild := false
                          ;scalafmt::test
                          ;test:scalafmt::test
                          ;sbt:scalafmt::test
                          ;scapegoat
                          ;scalafix --check
                          ;test:scalafix --check"
          requires:
            - compile
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - compile
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_json_tests: false
          run_duplication_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - test
            - lint
            - plugins_test
            - publish_docker_local
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
           name: tag_version
           context: CodacyAWS
           requires:
             - codacy/publish_docker
